[project]
name = "ncds"
version = "0.0.1"
requires-python= ">=3.10"
dependencies = [
    "numpy",
    "ml_collections",
    "absl-py",
    "scipy",
    "matplotlib",
    "jax",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
    "ruff",
    "black",
    "isort",
]
